
package Server_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GenerickiKontrolerServer", targetNamespace = "http://Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GenerickiKontrolerServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "prvaMetoda", targetNamespace = "http://Server/", className = "Server_client.PrvaMetoda")
    @ResponseWrapper(localName = "prvaMetodaResponse", targetNamespace = "http://Server/", className = "Server_client.PrvaMetodaResponse")
    public TransferObjekat prvaMetoda(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);

    
        /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "pocetnaVrednost", targetNamespace = "http://Server/", className = "Server_client.pocetnaVrednost")
    @ResponseWrapper(localName = "pocetnaVrednostResponse", targetNamespace = "http://Server/", className = "Server_client.pocetnaVrednostResponse")
    public TransferObjekat pocetnaVrednost(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);
    
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "azurirajPromene", targetNamespace = "http://Server/", className = "Server_client.azurirajPromene")
    @ResponseWrapper(localName = "azurirajPromeneResponse", targetNamespace = "http://Server/", className = "Server_client.azurirajPromeneResponse")
    public TransferObjekat azurirajPromene(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);
    
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "proveriPromene", targetNamespace = "http://Server/", className = "Server_client.proveriPromene")
    @ResponseWrapper(localName = "proveriPromeneResponse", targetNamespace = "http://Server/", className = "Server_client.proveriPromeneResponse")
    public TransferObjekat proveriPromene(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);
}

