
package Server_client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "KontrolerServer", targetNamespace = "http://Server/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface KontrolerServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "kreirajMatricu", targetNamespace = "http://Server/", className = "Server_client.KreirajMatricu")
    @ResponseWrapper(localName = "kreirajMatricuResponse", targetNamespace = "http://Server/", className = "Server_client.KreirajMatricuResponse")
    public TransferObjekat kreirajMatricu(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "apdejtujStatistikuIgraca", targetNamespace = "http://Server/", className = "Server_client.ApdejtujStatistikuIgraca")
    @ResponseWrapper(localName = "apdejtujStatistikuIgracaResponse", targetNamespace = "http://Server/", className = "Server_client.ApdejtujStatistikuIgracaResponse")
    public TransferObjekat apdejtujStatistikuIgraca(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "igracNaPotezu", targetNamespace = "http://Server/", className = "Server_client.IgracNaPotezu")
    @ResponseWrapper(localName = "igracNaPotezuResponse", targetNamespace = "http://Server/", className = "Server_client.IgracNaPotezuResponse")
    public TransferObjekat igracNaPotezu(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "postaviStatistikuIgraca", targetNamespace = "http://Server/", className = "Server_client.PostaviStatistikuIgraca")
    @ResponseWrapper(localName = "postaviStatistikuIgracaResponse", targetNamespace = "http://Server/", className = "Server_client.PostaviStatistikuIgracaResponse")
    public TransferObjekat postaviStatistikuIgraca(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "registrovanjeIgraca", targetNamespace = "http://Server/", className = "Server_client.RegistrovanjeIgraca")
    @ResponseWrapper(localName = "registrovanjeIgracaResponse", targetNamespace = "http://Server/", className = "Server_client.RegistrovanjeIgracaResponse")
    public TransferObjekat registrovanjeIgraca(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     * @throws InterruptedException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "proveriDaLiJeKrajIgre", targetNamespace = "http://Server/", className = "Server_client.ProveriDaLiJeKrajIgre")
    @ResponseWrapper(localName = "proveriDaLiJeKrajIgreResponse", targetNamespace = "http://Server/", className = "Server_client.ProveriDaLiJeKrajIgreResponse")
    public TransferObjekat proveriDaLiJeKrajIgre(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0)
        throws InterruptedException_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "azurirajMatricu", targetNamespace = "http://Server/", className = "Server_client.AzurirajMatricu")
    @ResponseWrapper(localName = "azurirajMatricuResponse", targetNamespace = "http://Server/", className = "Server_client.AzurirajMatricuResponse")
    public TransferObjekat azurirajMatricu(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns Server_client.TransferObjekat
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "proveraPrijavljivanja", targetNamespace = "http://Server/", className = "Server_client.ProveraPrijavljivanja")
    @ResponseWrapper(localName = "proveraPrijavljivanjaResponse", targetNamespace = "http://Server/", className = "Server_client.ProveraPrijavljivanjaResponse")
    public TransferObjekat proveraPrijavljivanja(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferObjekat arg0);

}
